"""empty message

Revision ID: 09c7af1e2706
Revises: 93a492cd711a
Create Date: 2020-05-16 15:17:04.102693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c7af1e2706'
down_revision = '93a492cd711a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('venue_id', sa.Integer(), nullable=False),
                    sa.Column('artist_id', sa.Integer(), nullable=False),
                    sa.Column('start_time', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
                    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
                    sa.PrimaryKeyConstraint('id', 'venue_id', 'artist_id')
                    )
    op.add_column(u'artist', sa.Column(
        'past_shows', sa.String(), nullable=True))
    op.add_column(u'artist', sa.Column('seeking_perf_description',
                                       sa.String(length=500), nullable=True))
    op.add_column(u'artist', sa.Column(
        'seeking_performance', sa.Boolean(), nullable=False))
    op.add_column(u'artist', sa.Column(
        'upcoming_shows', sa.String(), nullable=True))
    op.add_column(u'artist', sa.Column(
        'website', sa.String(length=120), nullable=True))
    op.alter_column(u'artist', 'genres', existing_type=sa.VARCHAR(
        length=120),
        nullable=False)
    op.add_column(u'venue', sa.Column(
        'genres', sa.ARRAY(sa.String(length=120)), nullable=False))
    op.add_column(u'venue', sa.Column(
        'past_shows', sa.String(), nullable=True))
    op.add_column(u'venue', sa.Column('seeking_tal_description',
                                      sa.String(length=500), nullable=True))
    op.add_column(u'venue', sa.Column(
        'seeking_talent', sa.Boolean(), nullable=False))
    op.add_column(u'venue', sa.Column(
        'upcoming_shows', sa.String(), nullable=True))
    op.add_column(u'venue', sa.Column(
        'website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'venue', 'website')
    op.drop_column(u'venue', 'upcoming_shows')
    op.drop_column(u'venue', 'seeking_talent')
    op.drop_column(u'venue', 'seeking_tal_description')
    op.drop_column(u'venue', 'past_shows')
    op.drop_column(u'venue', 'genres')
    op.alter_column(u'artist', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    op.drop_column(u'artist', 'website')
    op.drop_column(u'artist', 'upcoming_shows')
    op.drop_column(u'artist', 'seeking_performance')
    op.drop_column(u'artist', 'seeking_perf_description')
    op.drop_column(u'artist', 'past_shows')
    op.drop_table('show')
    # ### end Alembic commands ###
