"""empty message

Revision ID: c935d8fe1eaf
Revises: 09c7af1e2706
Create Date: 2020-05-16 15:43:44.929784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c935d8fe1eaf'
down_revision = '09c7af1e2706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.drop_column('artist', 'past_shows')
    op.drop_column('artist', 'upcoming_shows')
    op.add_column('venue', sa.Column('past_shows_count', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows_count', sa.String(), nullable=True))
    op.drop_column('venue', 'past_shows')
    op.drop_column('venue', 'upcoming_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('upcoming_shows', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('past_shows', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'upcoming_shows_count')
    op.drop_column('venue', 'past_shows_count')
    op.add_column('artist', sa.Column('upcoming_shows', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('past_shows', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'upcoming_shows_count')
    op.drop_column('artist', 'past_shows_count')
    # ### end Alembic commands ###
